# Default values for helm-blue-green.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginxdemos/hello
  tag: 0.3 # 0.1 , 0.2 , 0.3 , 0.4 are all available
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

blueGreen:
  scaleDownDelaySeconds: 30

linkerd:
  inject: enabled  # Set to "disabled" to skip Linkerd injection

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
