apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      release: {{ .Release.Name }}
  strategy:
    blueGreen:
      activeService: {{ .Release.Name }}
      previewService: {{ .Release.Name }}-preview
      autoPromotionEnabled: false
      scaleDownDelaySeconds: {{ .Values.blueGreen.scaleDownDelaySeconds }}
      # Analysis disabled due to Prometheus authentication requirements
      # prePromotionAnalysis:
      #   templates:
      #   - templateName: {{ .Release.Name }}-success-rate
      #   args:
      #   - name: service-name
      #     value: {{ .Release.Name }}-preview
      # postPromotionAnalysis:
      #   templates:
      #   - templateName: {{ .Release.Name }}-success-rate
      #   args:
      #   - name: service-name
      #     value: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        linkerd.io/inject: {{ .Values.linkerd.inject }}
      labels:
        app: {{ .Release.Name }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
