apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ .Release.Name }}-success-rate
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  args:
  - name: root-service-name
  - name: pod-template-hash
    valueFrom:
      fieldRef:
        fieldPath: metadata.labels['rollouts-pod-template-hash']
  - name: canary-pod-template-hash
  metrics:
  - name: success-rate
    interval: 30s
    count: 3
    successCondition: result[0] >= 0.95
    failureLimit: 2
    provider:
      prometheus:
        address: http://prometheus.linkerd-viz.svc.cluster.local:9090
        query: |
          sum(rate(response_total{app="{{`{{args.root-service-name}}`}}",rollouts_pod_template_hash="{{`{{args.pod-template-hash}}`}}",classification!="failure"}[1m])) / 
          sum(rate(response_total{app="{{`{{args.root-service-name}}`}}",rollouts_pod_template_hash="{{`{{args.pod-template-hash}}`}}"}[1m])) 